title: "electronic Computational Homotopy Theory"
subtitle: "Online Research Community"
author: "Jesse Keyes"
description: " "
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: true             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: eCHT, url: "https://echtorc.github.io/"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, url: "mailto:jessekeyes2@gmail.com"}
  - {title: Who we are, url: "https://echtorc.github.io/who-we-are/"}
  - {title: Research Seminar, url: "https://echtorc.github.io/echt-research-seminar"}
  - {title: Research Seminar Reading Group, url: "https://echtorc.github.io/echt-research-seminar-reading-group"}
  - {title: Reading Seminars, url: "https://echtorc.github.io/echt-reading-seminars"}
  - {title: Research Workshops, url: "https://echtorc.github.io/echt-research-workshops"}
  - {title: Courses, url: "https://echtorc.github.io/echt-courses"}
  - {title: Minicourses, url: "https://echtorc.github.io/echt-minicourses"}
  - {title: REU, url: "https://echtorc.github.io/echt-research-experience-for-undergraduates-summer-24"}
  - {title: Professional Development Activities, url: "https://echtorc.github.io/echt-professional-development"}
  - {title: Seminar on Machine Computation, url: "https://echtorc.github.io/echt-seminar-machine-computation"}

plugins:
 - jekyll-feed
